using TestClass;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TestClass.Tests
{
    [TestClass]
    public class Class1Tests
    {
        [TestMethod]
        public void FirstMethodTest()
        {
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void SecondMethodTest()
        {
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void ThirdMethodTest()
        {
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void ThirdMethodTest1()
        {
            Assert.Fail("autogenerated");
        }
    }
}